name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras

      - name: Format
        run: uv run make format

      - name: Lint
        run: uv run make lint

      - name: Run unit tests
        run: uv run pytest src/tests/unit -v

      - name: Run integration tests
        run: uv run pytest src/tests/integration -v

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            apt update -y
            apt install -y git curl
            
            if [ ! -d "/var/rashodomer-be/.git" ]; then
              git clone https://github.com/artempelyovin/rashodomer-be.git /var/rashodomer-be
            fi
            
            if ! command -v uv &> /dev/null; then
                curl -LsSf https://astral.sh/uv/install.sh | sh
            fi
            
            # add uv to PATH
            export PATH="$HOME/.local/bin:$PATH"
            
            cd /var/rashodomer-be
            git pull origin master
            
            if ! uv python list | grep -q "3.13"; then
              uv python install 3.13
            fi
            
            if [ ! -d ".venv" ]; then
              uv venv
            fi
            uv sync --no-dev
            
            SERVICE_FILE="/etc/systemd/system/rashodomer.service"
            sudo install -m 644 /var/rashodomer-be/deploy/rashodomer.service "$SERVICE_FILE"
            sudo systemctl daemon-reload
            sudo systemctl enable rashodomer
            echo "Installed or updated systemd service file"

            # restart and check status
            sudo systemctl restart rashodomer
            sleep 1
            sudo systemctl status --no-pager -l rashodomer || sudo journalctl -u rashodomer --no-pager -n 50
            exit 0
